### PR TITLE
Tuning PHP for importing large dumps

### PR DESCRIPTION
**Pull request by AntonTyutin**
Change upload file size not only for CLI but for FPM.
Setting of appropriate timeouts and memory limit.

### CODE REVIEW

**Comment by clue** [comment]
Awesome, changes LGTM!
Though I'm a bit surprised this wasn't covered earlier (#4).

Anyway, I'll leave this open for a few days (I'm on vacation the next days), in case anybody else wants to give some feedback and will merge this in then :+1:

**Comment by AntonTyutin** [comment]
Hi, Christian. What's about my PRs?

**Comment by clue** [comment]
> Hi, Christian. What's about my PRs?

Finally merged :shipit: :-)

Thanks for your patience Anton!

**Comment by AntonTyutin** [comment]
That's great! Thanks

**Pull request merged**
