### PR TITLE
MS SQL Server support

### PR DESCRIPTION
**Pull request by dmoreno**
Enable MS SQL support for adminer

### CODE REVIEW

**Comment by clue** [comment]
Thanks for your PR!

I'm not an MS SQL Server expert, so I can't really give much feedback on this.

Adding the PHP extension certainly makes sense, but is the dummy configuration really required?

@all: Any feedback is much appreciated!

**Comment by dmoreno** [comment]
I changed PR to comment unnecessary example lines. Important lines are:

<pre>
[global]
        tds version = 8.0
</pre>

**Comment by clue** [comment]
Let's get this in! :-)

Thanks!

**Comment by kusmierz** [comment]
@dmoreno could you test mssql support in #21?

**Pull request merged**
