### PR TITLE
use official php alpine image

### LINKED ISSUE #13: Migrate to official php image
I see that instead of an official PHP base image this project uses a custom setup with nginx + php-fpm which requires supervisord to manage both services. So this is not in line with the recommended docker paradigm of one process per container.

It also seems to slow down the shutdown of this image. In a setup with 5 containers, it's always adminer that I have to wait for.

So would you consider a migration to the official apache based PHP image? It would make the Dockerfile simpler and take the burden of installing PHP from you. You still can tweak the PHP config though, if you want to.

### LINKED ISSUE #16: switch to an Alpine based image
This is the official phpmyadmin Dockerfile that we can imitate:
https://github.com/phpmyadmin/docker/blob/master/Dockerfile

The image size is 55MB. While this Adminer image is 218MB.

### LINKED ISSUE #17: Pass signals to supervisord to support stopping cleanly
Current form of CMD does not passes signals to the supervisord and container can not be stopped via standard `docker stop` command. After a timeout, container is killed by Docker.

### PR DESCRIPTION
**Pull request by mathroc**
this Dockfile is based on php:7.0-alpine and does not install nginx, fpm or apache. it only use `php -S`. It seems to works fine with the very basic test I'v done connecting to a postgresql database.

please share your thoughts on this and test it if you can

todo:

 * [x] alpine image closes #16 
 * [x] official php image closes #13
 * [ ] install mssql extension
 * [x] php.ini settings
 * [x] wrap with [tini](https://github.com/krallin/tini) to closes #17
 * [ ] add other PDO drivers ? (eg: #15)

/ping @mikehaertl

### CODE REVIEW

**Comment by mathroc** [comment]
I took a quick look at mssql with php7, apparently there is a few options but I don't know which works or not:

 * pdo_dblib <= deprecated ?
 * odbc
 * pdo_odbc

anyone knows which one would work ?

**Comment by mathroc** [comment]
@kusmierz well, as you've seen when trying with php 7, supports for the mssql extension was dropped and it seems it's now harder to use php with mssql on linux.

I'm looking at how to install odbc or pdo_odbc but they needs some dependencies I don't know how to get and I don't even know if those are enough to support mssql servers (I've never worked with mssql)

so either I figure out how to install odbc extension and someone can confirm it's enough or we have to stick with with php 5.6 (that would be a PITA)

@clue alternatively how about another branch (and another tag on docker hub) for alpine until everything is supported properly? it would be easier for others to test the alpine branch and would not break everyone still using `latest`.
also because until docker-library/php#206 is merged, the alpine image will actually be bigger than the current one

**Comment by mikehaertl** [comment]
@mathroc @kusmierz Regarding mssql and odbc: I would focus on the main features. Adminer was mainly written with MySQL in mind. So if this works, I'd say the main job is done. Anything else is bonus. It can either be added in a later release. Or if someone really needs it, he can build his own image using this here as a base image.

> also because until docker-library/php#206 is merged, the alpine image will actually be bigger than the current one

I wonder if we couldn't also use the apache based official image. Not sure if alpine is really worth the extra hassle. The thing with alpine images is, that even the official PHP image is not that much smaller than the debian/apache based. In that case we would also not need `tini`. I've not used it before, but I always like having as few processes in my container as possible. Even if it's only a init daemon.

**Comment by mathroc** [comment]
closing in favor of #21

**Comment by clue** [comment]
> @clue alternatively how about another branch (and another tag on docker hub) for alpine until everything is supported properly? it would be easier for others to test the alpine branch and would not break everyone still using latest.

I'm not opposed to getting another branch set up in the meantime :+1: I think we agree that the goal should be an image that is as easy to use as possible, so a single branch should probably be our (perhaps mid term) goal here.

> Regarding mssql and odbc: I would focus on the main features. Adminer was mainly written with MySQL in mind.

I understand where you're coming from and personally have yet to use this image with MSSQL. However, there are people that use this image with alternative databases (#7), so I'm not a big fan of dropping this for merely this:

> Not sure if alpine is really worth the extra hassle.

So far we're *only* talking about an optimization (which I think is a good thing!). I agree, personally I'm not yet convinced this alone warrants dropping features, so I'm curious how #21 will end up :+1:

**Pull request closed without merging**
